# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HackfestBrogrammers' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HackfestBrogrammers
	pod 'SwiftyJSON'
 	pod 'Alamofire', '4.5.1'
 	pod 'UITextView+Placeholder'
	pod 'Kingfisher'
	pod 'IQKeyboardManagerSwift', '5.0.0'
	
	#Pods for GoogleMaps
	pod 'GoogleMaps'
  	pod 'GooglePlaces'
 	pod 'GooglePlacePicker'

end
